/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register a new user account. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UserRegister"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UserResponse"];
                    };
                };
                422: components["responses"]["UNPROCESSABLE_CONTENT"];
                default: components["responses"]["DEFAULT_ERROR"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Authenticate user credentials and issue JWT access token. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UserLogin"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TokenResponse"];
                    };
                };
                422: components["responses"]["UNPROCESSABLE_CONTENT"];
                default: components["responses"]["DEFAULT_ERROR"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh JWT access token. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                default: components["responses"]["DEFAULT_ERROR"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout user and revoke active token. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                default: components["responses"]["DEFAULT_ERROR"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/forgot-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Request password reset link/token. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                default: components["responses"]["DEFAULT_ERROR"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/reset-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reset password using reset token. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                default: components["responses"]["DEFAULT_ERROR"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/verify-email": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Verify user email address. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                default: components["responses"]["DEFAULT_ERROR"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/products/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Retrieve list of all product categories. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CategoryResponse"][];
                    };
                };
                default: components["responses"]["DEFAULT_ERROR"];
            };
        };
        put?: never;
        /** Create a new product category (Admin). */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CategoryCreate"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CategoryResponse"];
                    };
                };
                422: components["responses"]["UNPROCESSABLE_CONTENT"];
                default: components["responses"]["DEFAULT_ERROR"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/products/categories/{category_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                category_id: string;
            };
            cookie?: never;
        };
        get?: never;
        /** Update category details (Admin). */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    category_id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CategoryUpdate"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CategoryResponse"];
                    };
                };
                422: components["responses"]["UNPROCESSABLE_CONTENT"];
                default: components["responses"]["DEFAULT_ERROR"];
            };
        };
        post?: never;
        /** Delete category (Admin). */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    category_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                default: components["responses"]["DEFAULT_ERROR"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Retrieve active products with search, category filtering, sorting, and pagination. */
        get: {
            parameters: {
                query?: {
                    /** @description Search term in name or description */
                    search?: string;
                    /** @description Filter by category ID */
                    category_id?: string;
                    sort_by?: "price_asc" | "price_desc" | "created_at";
                    page?: number;
                    per_page?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProductResponse"][];
                    };
                };
                422: components["responses"]["UNPROCESSABLE_CONTENT"];
                default: components["responses"]["DEFAULT_ERROR"];
            };
        };
        put?: never;
        /** Create a new product and populate the Redis inventory pool (Admin). */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ProductCreate"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProductResponse"];
                    };
                };
                422: components["responses"]["UNPROCESSABLE_CONTENT"];
                default: components["responses"]["DEFAULT_ERROR"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/products/{product_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                product_id: string;
            };
            cookie?: never;
        };
        /** Retrieve detailed product information by ID. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    product_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProductResponse"];
                    };
                };
                default: components["responses"]["DEFAULT_ERROR"];
            };
        };
        /** Update product details (Admin). */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    product_id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ProductUpdate"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProductResponse"];
                    };
                };
                422: components["responses"]["UNPROCESSABLE_CONTENT"];
                default: components["responses"]["DEFAULT_ERROR"];
            };
        };
        post?: never;
        /** Deactivate/Delete product (Admin). */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    product_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                default: components["responses"]["DEFAULT_ERROR"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/products/{product_id}/variants": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                product_id: string;
            };
            cookie?: never;
        };
        /** List variants for a specific product. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    product_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProductVariantResponse"][];
                    };
                };
                default: components["responses"]["DEFAULT_ERROR"];
            };
        };
        put?: never;
        /** Create a new product variant (Admin). */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    product_id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ProductVariantCreate"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProductVariantResponse"];
                    };
                };
                422: components["responses"]["UNPROCESSABLE_CONTENT"];
                default: components["responses"]["DEFAULT_ERROR"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/products/{product_id}/variants/{variant_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                product_id: string;
                variant_id: string;
            };
            cookie?: never;
        };
        get?: never;
        /** Update a product variant (Admin). */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    product_id: string;
                    variant_id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ProductVariantUpdate"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProductVariantResponse"];
                    };
                };
                422: components["responses"]["UNPROCESSABLE_CONTENT"];
                default: components["responses"]["DEFAULT_ERROR"];
            };
        };
        post?: never;
        /** Delete a product variant (Admin). */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    product_id: string;
                    variant_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                default: components["responses"]["DEFAULT_ERROR"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/products/{product_id}/sync-stock": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                product_id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Force synchronize Redis inventory cache with PostgreSQL DB state (Admin). */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    product_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                default: components["responses"]["DEFAULT_ERROR"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cart": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the current authenticated user's shopping cart. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CartResponse"];
                    };
                };
                default: components["responses"]["DEFAULT_ERROR"];
            };
        };
        put?: never;
        post?: never;
        /** Clear all items from user's shopping cart. */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                default: components["responses"]["DEFAULT_ERROR"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cart/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add a product item or SKU variant to the shopping cart. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AddToCart"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CartItemResponse"];
                    };
                };
                422: components["responses"]["UNPROCESSABLE_CONTENT"];
                default: components["responses"]["DEFAULT_ERROR"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cart/items/{item_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove a specific item from the cart. */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    item_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                default: components["responses"]["DEFAULT_ERROR"];
            };
        };
        options?: never;
        head?: never;
        /** Update item quantity in cart. */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    item_id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateCartItem"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CartItemResponse"];
                    };
                };
                422: components["responses"]["UNPROCESSABLE_CONTENT"];
                default: components["responses"]["DEFAULT_ERROR"];
            };
        };
        trace?: never;
    };
    "/api/v1/orders/reserve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Core Flash Sale Endpoint.
         *     Requires Idempotency-Key header. Decrements stock via Lua script, saves order & outbox event.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["OrderReserve"];
                };
            };
            responses: {
                /** @description Accepted */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ReservationAccepted"];
                    };
                };
                422: components["responses"]["UNPROCESSABLE_CONTENT"];
                default: components["responses"]["DEFAULT_ERROR"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orders/checkout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Checkout Multi-Item Cart Endpoint.
         *     Requires Idempotency-Key header. Atomically reserves stock for all cart items, creates order & outbox event, and clears cart.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Accepted */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ReservationAccepted"];
                    };
                };
                default: components["responses"]["DEFAULT_ERROR"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orders/guest-checkout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Guest Checkout Endpoint.
         *     Does not require JWT auth. Accepts email, item list, and idempotency key.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Accepted */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ReservationAccepted"];
                    };
                };
                default: components["responses"]["DEFAULT_ERROR"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orders/{order_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                order_id: string;
            };
            cookie?: never;
        };
        /** Retrieve details and status for a specific order. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    order_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["OrderResponse"];
                    };
                };
                default: components["responses"]["DEFAULT_ERROR"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Retrieve list of orders for the authenticated user. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["OrderResponse"][];
                    };
                };
                default: components["responses"]["DEFAULT_ERROR"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orders/{order_id}/pay": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                order_id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Process payment for an active reservation before the 10-minute expiry (Development Progress Stub). */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    order_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                default: components["responses"]["DEFAULT_ERROR"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orders/payments/intent": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a Stripe PaymentIntent for a pending order. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["PaymentIntentRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PaymentIntentResponse"];
                    };
                };
                422: components["responses"]["UNPROCESSABLE_CONTENT"];
                default: components["responses"]["DEFAULT_ERROR"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orders/{order_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                order_id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel active reservation and immediately release inventory back to pool. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    order_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                default: components["responses"]["DEFAULT_ERROR"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/coupons/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Validate a promo code for discount applicability. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                default: components["responses"]["DEFAULT_ERROR"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/coupons": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a new promotional coupon code (Admin). */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                default: components["responses"]["DEFAULT_ERROR"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/products/{product_id}/reviews": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                product_id: string;
            };
            cookie?: never;
        };
        /** List customer reviews for a product. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    product_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                default: components["responses"]["DEFAULT_ERROR"];
            };
        };
        put?: never;
        /** Submit a product review and rating (1-5 stars). */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    product_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                default: components["responses"]["DEFAULT_ERROR"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/wishlist": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the authenticated user's wishlist/favorites. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                default: components["responses"]["DEFAULT_ERROR"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/wishlist/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add a product to wishlist. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                default: components["responses"]["DEFAULT_ERROR"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/wishlist/items/{item_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove an item from wishlist. */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    item_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                default: components["responses"]["DEFAULT_ERROR"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/shipping-addresses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List saved shipping addresses for user. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                default: components["responses"]["DEFAULT_ERROR"];
            };
        };
        put?: never;
        /** Add a new shipping address. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                default: components["responses"]["DEFAULT_ERROR"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/webhooks/stripe": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Signature-verified Stripe Webhook Handler.
         *     Reconciles order state asynchronously on payment events.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                default: components["responses"]["DEFAULT_ERROR"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness check probe. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                default: components["responses"]["DEFAULT_ERROR"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Readiness probe checking database and redis dependencies. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                default: components["responses"]["DEFAULT_ERROR"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Retrieve high-level system telemetry and aggregate metrics (Admin). */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                default: components["responses"]["DEFAULT_ERROR"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/outbox": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Retrieve recent Transactional Outbox events for event stream monitoring (Admin). */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                default: components["responses"]["DEFAULT_ERROR"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Retrieve user account listing (Admin). */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                default: components["responses"]["DEFAULT_ERROR"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Retrieve all orders with optional status filtering (Admin). */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                default: components["responses"]["DEFAULT_ERROR"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/orders/{order_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                order_id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update order status (e.g., SHIPPED, DELIVERED, REFUNDED) and fulfillment tracking (Admin). */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    order_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                default: components["responses"]["DEFAULT_ERROR"];
            };
        };
        trace?: never;
    };
    "/api/v1/admin/task-logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Retrieve background Celery task execution logs (Admin). */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                default: components["responses"]["DEFAULT_ERROR"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            /** @description Error code */
            code?: number;
            /** @description Error name */
            status?: string;
            /** @description Error message */
            message?: string;
            /** @description Errors */
            errors?: {
                [key: string]: unknown;
            };
        };
        PaginationMetadata: {
            /** @description Total number of items. */
            total?: number;
            /** @description Total number of pages. */
            total_pages?: number;
            /** @description First available page number. */
            first_page?: number;
            /** @description Last available page number. */
            last_page?: number;
            /** @description Current page number. */
            page?: number;
            /** @description Previous page number. */
            previous_page?: number;
            /** @description Next page number. */
            next_page?: number;
        };
        UserRegister: {
            /**
             * Format: email
             * @description User email address
             */
            email: string;
            /** @description Password (min 8 characters) */
            password: string;
            /** @description Full name */
            full_name?: string;
        };
        UserResponse: {
            readonly id?: string;
            /** Format: email */
            readonly email?: string;
            readonly full_name?: string;
            readonly role?: string;
            readonly is_active?: boolean;
            readonly created_at?: string;
        };
        UserLogin: {
            /**
             * Format: email
             * @description User email address
             */
            email: string;
            /** @description User password */
            password: string;
        };
        TokenResponse: {
            access_token: string;
            token_type?: string;
            expires_in: number;
            user: components["schemas"]["UserResponse"];
        };
        CategoryResponse: {
            readonly id?: string;
            readonly name?: string;
            readonly slug?: string;
            readonly description?: string;
            readonly parent_id?: string;
            readonly created_at?: string;
        };
        CategoryCreate: {
            /** @description Category name */
            name: string;
            /** @description URL slug */
            slug?: string;
            /** @description Category description */
            description?: string;
            /** @description Parent category UUID */
            parent_id?: string;
        };
        CategoryUpdate: {
            /** @description Category name */
            name?: string;
            /** @description URL slug */
            slug?: string;
            /** @description Category description */
            description?: string;
            /** @description Parent category UUID */
            parent_id?: string;
        };
        ProductVariantResponse: {
            readonly id?: string;
            readonly product_id?: string;
            readonly sku?: string;
            readonly name?: string;
            readonly size?: string;
            readonly color?: string;
            readonly price?: number;
            readonly total_stock?: number;
            readonly available_stock?: number;
        };
        ProductResponse: {
            readonly id?: string;
            readonly category_id?: string;
            readonly category_name?: string;
            readonly name?: string;
            readonly sku?: string;
            readonly description?: string;
            readonly images?: string[];
            readonly total_stock?: number;
            readonly available_stock?: number;
            readonly price?: number;
            readonly is_active?: boolean;
            readonly version?: number;
            readonly variants?: components["schemas"]["ProductVariantResponse"][];
            readonly created_at?: string;
        };
        ProductVariantCreate: {
            sku: string;
            name: string;
            size?: string;
            color?: string;
            price: number;
            /** @default 0 */
            total_stock: number;
            /** @default 0 */
            available_stock: number;
        };
        ProductCreate: {
            /** @description Product name */
            name: string;
            /** @description Unique SKU code */
            sku: string;
            /** @description Initial total stock quantity */
            total_stock: number;
            /** @description Unit price */
            price: number;
            category_id?: string;
            description?: string;
            images?: string[];
            variants?: components["schemas"]["ProductVariantCreate"][];
        };
        ProductUpdate: {
            name?: string;
            sku?: string;
            price?: number;
            total_stock?: number;
            available_stock?: number;
            category_id?: string;
            description?: string;
            images?: string[];
            is_active?: boolean;
            variants?: components["schemas"]["ProductVariantCreate"][];
        };
        ProductVariantUpdate: {
            sku?: string;
            name?: string;
            size?: string;
            color?: string;
            price?: number;
            total_stock?: number;
            available_stock?: number;
        };
        CartItemResponse: {
            readonly id?: string;
            readonly user_id?: string;
            readonly product_id?: string;
            readonly product_name?: string;
            readonly variant_id?: string;
            readonly variant_name?: string;
            readonly variant_sku?: string;
            readonly quantity?: number;
            readonly unit_price?: number;
            readonly subtotal?: number;
            readonly created_at?: string;
        };
        CartResponse: {
            readonly items?: components["schemas"]["CartItemResponse"][];
            readonly subtotal?: number;
            readonly item_count?: number;
        };
        AddToCart: {
            /** @description UUID of product to add to cart */
            product_id: string;
            /** @description Optional UUID of specific product SKU variant */
            variant_id?: string;
            /**
             * @description Quantity to add (default: 1)
             * @default 1
             */
            quantity: number;
        };
        UpdateCartItem: {
            /** @description New quantity for cart item */
            quantity: number;
        };
        OrderReserve: {
            /** @description UUID of product to reserve */
            product_id: string;
            /** @description Optional UUID of product variant to reserve */
            variant_id?: string;
            /** @description Quantity of stock to reserve */
            quantity: number;
        };
        OrderItemResponse: {
            readonly id?: string;
            readonly order_id?: string;
            readonly product_id?: string;
            readonly product_name?: string;
            readonly variant_id?: string;
            readonly variant_name?: string;
            readonly variant_sku?: string;
            readonly quantity?: number;
            readonly unit_price?: number;
            readonly subtotal?: number;
        };
        OrderResponse: {
            readonly id?: string;
            readonly user_id?: string;
            readonly product_id?: string;
            readonly status?: string;
            readonly quantity?: number;
            readonly unit_price?: number;
            readonly subtotal?: number;
            readonly tax?: number;
            readonly shipping_fee?: number;
            readonly total_amount?: number;
            readonly idempotency_key?: string;
            readonly expires_at?: string;
            readonly created_at?: string;
            readonly items?: components["schemas"]["OrderItemResponse"][];
        };
        ReservationAccepted: {
            readonly message?: string;
            readonly order?: components["schemas"]["OrderResponse"];
            readonly task_id?: string;
            readonly status_url?: string;
        };
        PaymentIntentRequest: {
            /** @description Target order ID */
            order_id: string;
            /**
             * @description ISO currency code
             * @default usd
             */
            currency: string;
        };
        PaymentIntentResponse: {
            readonly payment_intent_id?: string;
            readonly client_secret?: string;
            readonly amount?: number;
            readonly currency?: string;
            readonly status?: string;
            readonly mode?: string;
            readonly message?: string;
        };
    };
    responses: {
        /** @description Unprocessable Content */
        UNPROCESSABLE_CONTENT: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Default error response */
        DEFAULT_ERROR: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;

/* Domain helper types */
export interface User {
  id: string;
  email: string;
  full_name?: string;
  role: 'user' | 'admin';
  is_active: boolean;
  is_email_verified: boolean;
  created_at?: string;
}

export interface AuthResponse {
  access_token: string;
  token_type: string;
  expires_in?: number;
  user: User;
}

export interface Category {
  id: string;
  name: string;
  slug: string;
  description?: string;
  parent_id?: string;
  created_at?: string;
}

export interface ProductVariant {
  id: string;
  product_id: string;
  sku: string;
  name: string;
  size?: string;
  color?: string;
  price: number;
  total_stock: number;
  available_stock: number;
}

export interface Product {
  id: string;
  name: string;
  sku: string;
  description?: string;
  price: number;
  total_stock: number;
  available_stock: number;
  category_id?: string;
  category?: Category;
  images: string[];
  is_active: boolean;
  variants?: ProductVariant[];
  created_at?: string;
}

export interface CartItem {
  id: string;
  user_id: string;
  product_id: string;
  variant_id?: string;
  quantity: number;
  product?: Product;
  variant?: ProductVariant;
  unit_price: number;
  subtotal: number;
}

export interface Cart {
  items: CartItem[];
  subtotal: number;
  item_count: number;
}

export type OrderStatus = 'PENDING' | 'PAID' | 'SHIPPED' | 'DELIVERED' | 'CANCELLED' | 'REFUNDED' | 'RETURNED';

export interface OrderItem {
  id: string;
  order_id: string;
  product_id: string;
  variant_id?: string;
  product_name: string;
  quantity: number;
  unit_price: number;
  subtotal: number;
  product?: Product;
}

export interface Order {
  id: string;
  user_id?: string;
  guest_email?: string;
  status: OrderStatus;
  total_amount: number;
  tax_amount: number;
  discount_amount: number;
  items: OrderItem[];
  shipping_address?: ShippingAddress;
  created_at: string;
  updated_at?: string;
}

export interface Coupon {
  id: string;
  code: string;
  discount_type: 'percentage' | 'fixed';
  discount_value: number;
  min_order_amount: number;
  usage_limit?: number;
  times_used?: number;
  expires_at?: string | null;
  is_active: boolean;
  created_at?: string;
}

export interface CouponValidation {
  valid: boolean;
  code?: string;
  discount_type?: 'percentage' | 'fixed';
  discount_value?: number;
  calculated_discount?: number;
  message?: string;
}

export interface Review {
  id: string;
  product_id: string;
  user_id: string;
  rating: number;
  title?: string;
  comment?: string;
  created_at: string;
  user_name?: string;
}

export interface WishlistItem {
  id: string;
  user_id: string;
  product_id: string;
  product?: Product;
  created_at?: string;
}

export interface ShippingAddress {
  id?: string;
  user_id?: string;
  recipient_name: string;
  address_line1: string;
  address_line2?: string;
  city: string;
  state: string;
  postal_code: string;
  country: string;
  phone?: string;
}

export interface ApiError {
  type?: string;
  title?: string;
  status?: number;
  detail?: string;
  message?: string;
}
